/*DROP TABLES,VIEW*/
DROP TABLE AIRWAYS.PASSENGER;

DROP TABLE AIRWAYS.TICKET;

DROP TABLE AIRWAYS.PAYMENT;

DROP TABLE AIRWAYS.CARDDETAILS;

DROP TABLE AIRWAYS.FLIGHT;

DROP TABLE AIRWAYS.FLIGHTSCHEDULE;

DROP TABLE AIRWAYS.AIRPORT;

DROP TABLE AIRWAYS.EMPLOYEE;

DROP VIEW AIRWAYS.PASSENGERRECORD;