/*GET TICKET ID WITH PAYMENT DETAILS*/
SELECT AIRWAYS.TICKET.TICKETID,SEATNUMBER,AIRWAYS.PAYMENT.PAYMENTID,PAYMENTAMOUNT FROM AIRWAYS.TICKET INNER JOIN AIRWAYS.PAYMENT ON AIRWAYS.TICKET.SSN= AIRWAYS.PAYMENT.SSN ORDER BY AIRWAYS.TICKET.TICKETID ASC;

/*GET AIRPORT DETAILS,FLIGHT DETAILS, FLIGHT SCHEDULE*/
SELECT AIRWAYS.AIRPORT.AIRPORTID,AIRPORTNAME,LOCATION,AIRWAYS.FLIGHT.FLIGHTNUMBER,FLIGHTTYPE,CAPACITY,AIRWAYS.FLIGHTSCHEDULE.ARRIVALTIME,DEPARTURETIME,ARRIVALLOCATION,DEPARTURELOCATION 
FROM AIRWAYS.AIRPORT INNER JOIN (AIRWAYS.FLIGHT INNER JOIN AIRWAYS.FLIGHTSCHEDULE ON AIRWAYS.FLIGHT.FLIGHTNUMBER = AIRWAYS.FLIGHTSCHEDULE.FLIGHTNUMBER) 
ON (AIRWAYS.AIRPORT.FLIGHTNUMBER = AIRWAYS.FLIGHT.FLIGHTNUMBER) 
ORDER BY AIRWAYS.FLIGHT.FLIGHTNUMBER ASC;

/*GET EMPLOYEE DETAILS WITH FLIGHT DETAILS AND AIRPORT DETAILS*/
SELECT AIRWAYS.EMPLOYEE.EMPLOYEEID,NAME, AIRWAYS.AIRPORT.AIRPORTID,AIRPORTNAME,LOCATION,AIRWAYS.FLIGHT.FLIGHTNUMBER 
FROM AIRWAYS.AIRPORT INNER JOIN (AIRWAYS.FLIGHT INNER JOIN AIRWAYS.EMPLOYEE ON AIRWAYS.FLIGHT.EMPLOYEEID = AIRWAYS.EMPLOYEE.EMPLOYEEID) 
ON (AIRWAYS.AIRPORT.FLIGHTNUMBER = AIRWAYS.FLIGHT.FLIGHTNUMBER) 
ORDER BY AIRWAYS.EMPLOYEE.EMPLOYEEID ASC;

/*GET PASSENGER DETAILS WITH TICKET DETAILS FLIGHT NUMBER PAYMENT ID AND AIRPORT NAME AND LOCATION*/
SELECT AIRWAYS.PASSENGER.NAME,ADDRESS,AIRWAYS.FLIGHT.FLIGHTNUMBER, AIRWAYS.PAYMENT.PAYMENTID,AIRWAYS.AIRPORT.AIRPORTNAME,LOCATION 
FROM AIRWAYS.AIRPORT 
INNER JOIN (AIRWAYS.FLIGHT 
INNER JOIN (AIRWAYS.PASSENGER 
INNER JOIN (AIRWAYS.TICKET INNER JOIN AIRWAYS.PAYMENT ON AIRWAYS.TICKET.TICKETID = AIRWAYS.PAYMENT.TICKETID)
ON AIRWAYS.PASSENGER.SSN = AIRWAYS.TICKET.SSN)
ON AIRWAYS.FLIGHT.FLIGHTNUMBER = AIRWAYS.TICKET.FLIGHTNUMBER)
ORDER BY AIRWAYS.FLIGHT.FLIGHTNUMBER DESC;

/*GET TOTAL AMOUNT RECIEVED FROM SPECIFIC PASSENGER*/
SELECT SUM(PAYMENTAMOUNT), SSN
FROM PAYMENT
GROUP BY PAYMENTID;

/*GET TOTAL CAPACITY OF FLIGHT ACCORDING TO ITS TYPE*/
SELECT SUM(CAPACITY),FLIGHTNUMBER, FLIGHTTYPE
FROM FLIGHT
GROUP BY FLIGHTTYPE;